name: Test

on:
  push:
    branches: [ master ]
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: yarn install
    - run: yarn test
      env:
        CI: true
  e2esetup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: e2e-yarn-${{ hashFiles('**\yarn.lock') }}
          restore-keys: e2e-yarn-
      - run: yarn
  e2etests:
    needs: [e2esetup]
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chrome,firefox]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore node_modules cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: e2e-yarn-${{ hashFiles('**\yarn.lock') }}
          restore-keys: e2e-yarn-
      - run: yarn
      - name: Run test
        run: yarn test:e2e
        env:
          BROWSER: ${{ matrix.browser }}
